ExistingApplication/EmcureCERI.Web/Controllers/DRFInitializationController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using EmcureCERI.Business.Contract.ServiceContracts;
using EmcureCERI.Data.DataAccess.Entities;
using EmcureCERI.Web.Classes;
using EmcureCERI.Web.Helper;
using EmcureCERI.Web.Hubs;
using EmcureCERI.Web.Models;
using EmcureCERI.Web.Models.DRFViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;


namespace EmcureCERI.Web.Controllers
{
    [Authorize]
    public class DRFInitializationController : Controller
    {
        //Test
        private readonly IConfiguration _config;
        private readonly IDRFInitialization _drfINI;
        private readonly EmcureCERIDBContext _db;
        private readonly IDRFManufacturing _drfMAN;
        private readonly IDRFSupplyChainManagement _drfSCM;
        private readonly IDRFRA _drfRA;
        private readonly IDRFIP _drfIP ;
        private readonly IDRFFinance _dRFFinance;
        private readonly IDRFFinal _dRFFinal;
        private readonly IDRFMedical _dRFMedical;
        private readonly ISMTPService _sMTPService;
        private readonly IEmailService _emailService;
        IHostingEnvironment _env;
        private readonly IHubContext<NotificationHub> _notificationHubContext;
        public DRFInitializationController(IHostingEnvironment env,IConfiguration config, IDRFInitialization INI,IDRFManufacturing MAN,IDRFSupplyChainManagement SCM,IDRFRA RA,IDRFIP IP,IDRFFinance Finance,IDRFFinal Final, IDRFMedical Medical, IHubContext<NotificationHub> notificationHubContext, IEmailService emailService, ISMTPService sMTPService)
        {
            _config = config;
            this._drfINI = INI;
            this._drfMAN = MAN;
            _db = new EmcureCERIDBContext();
            this._drfSCM = SCM;
            this._drfRA = RA;
            this._drfIP = IP;
            this._dRFFinance = Finance;
            this._dRFFinal = Final;
            this._dRFMedical = Medical;
            this._env = env;
            _notificationHubContext = notificationHubContext;
            _emailService = emailService;
            _sMTPService = sMTPService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult DRFInitialization()
        {
            return View();
        }

        public IActionResult DRFInitializationApproval(int ID)
        {
           var data= (from i in _db.Tbl_DRF_Initialization
                      join c in _db.Master_Country on i.CountryID equals c.Id
                      join s in _db.Tbl_Master_PIDFStatus on i.StatusID equals s.PidfStatusID
                      join TMF in _db.Tbl_Master_Formulation on i.Form equals TMF.Id
                      join TMS in _db.Tbl_Master_Strength on i.Strength equals TMS.Id
                      join TMP in _db.Tbl_Master_PackSize on i.PackSize equals TMP.Id
                      join TMPSS in _db.Tbl_Master_PackStyle on i.PackStyle equals TMPSS.Id
                      //join TMPM in _db.Tbl_Master_ProductManufacture on i.Plant equals TMPM.Id
                      from TMPM in _db.Tbl_Master_ProductManufacture.Where(o => o.Id == i.Plant).DefaultIfEmpty()
                      join TMM in _db.Tbl_Master_ModeofFeesPayment on i.ModeOfFeesPayment equals TMM.Id
                      join TMMS in _db.Tbl_Master_Modeofshipment on i.ModeOfShipment equals TMMS.Id
                      //join TMDT in _db.Tbl_Master_DossierTemplate on i.DossierTemplateID equals TMDT.Id
                      from TMDT in _db.Tbl_Master_DossierTemplate.Where(n => n.Id == i.DossierTemplateID).DefaultIfEmpty()
                      join TMI in _db.Tbl_Master_Incoterms on i.Incoterms equals TMI.Id
                      where i.InitializationID== ID
             select new
             {
                   i.InitializationID
                  ,i.CountryID
                  ,c.Country
                  ,i.GenericName
                  ,i.BrandName
                  ,i.TreadmarkApprovedInternal
                  ,i.TreadmarkSuggestedInternal
                  ,i.TreadmarkOwnerInternal
                  ,//i.Form
                 Form = TMF.Formulation
                             ,
                 //i.Strength
                 Strength = TMS.Strength
                             ,
                 //i.PackSize
                 PackSize = TMP.PackSize
                             ,
                 //i.PackStyle
                 PackStyle = TMPSS.PackStyle
                             ,
                 //i.Plant
                 Plant = TMPM.ProductManufacture
                  ,
                 i.RegistrationFees
                  ,i.FeesToBePaidBy
                  ,//i.ModeOfFeesPayment
                 ModeOfFeesPayment = TMM.ModeofFeesPayment
                  ,
                 i.MAHolder
                  ,i.ProposedMarketingStatus
                  ,i.ShippingPort
                  ,//i.ModeOfShipment
                 ModeOfShipment = TMMS.Modeofshipment
                             ,
                 //i.Incoterms
                 Incoterms = TMI.Incoterms
                  ,
                 i.DossierSubmittedToMOHBy
                  ,i.OwnerOfRegistration
                  ,i.AvailabilityofCDA
                  ,i.MarketSize
                  ,i.ThreeYearCAGR
                  ,i.NumberOfCurrentPlayer
                  ,i.InnovatorBrand
                  ,i.FirstBrand
                  ,i.SecondBrand
                  ,i.ThirdBrand
                  ,i.ExpectedMarketValueGrowth
                  ,i.InnavotorName
                  ,i.MSFirstBrand
                  ,i.MSSecondBrand
                  ,i.MSThirdBrand
                  ,i.Partner
                  ,i.FirstYearForecastUnitsPacks
                  ,i.SecondYearForecastUnitsPacks
                  ,i.ThirdYearForecastUnitsPacks
                  ,i.FirstYearForecastPriceToPatient
                  ,i.SecondYearForecastPriceToPatient
                  ,i.ThirdYearForecastPriceToPatient
                  ,i.FirstYearForecastCIF
                  ,i.SecondYearForecastCIF
                  ,i.ThirdYearForecastCIF
                  ,i.FirstYearForecastValue
                  ,i.SecondYearForecastValue
                  ,i.ThirdYearForecastValue
                  ,i.OrderFrequency
                  ,i.NameDossierSend
                  ,i.AddressDossierSend
                  ,i.StrategyAlignment
                  ,i.ExceptionExplained
                  ,i.StatusID
                  ,s.PidfStatus
                   ,
                 i.DossierTemplateID
                    ,
                 TMDT.DossierTemplate,
                 i.Currency
                 ,i.TSExcecuted
                 ,i.DAExcecuted
                 ,i.EmailDossierSend
                 ,i.PhoneDossierSend
                 ,i.IsSamples_Required
                 ,i.Samples_Required
                 ,i.Remark
             }).FirstOrDefault();

            var AttachedPIDFID = (from i in _db.Tbl_DRF_Initialization
                                  join p in _db.Tbl_DRF_PIDF_Mapping on i.InitializationID equals p.DRFID
                                  where i.InitializationID == ID
                                  select new { 
                                  
                                      p.ID
                                  
                                  }).FirstOrDefault();

            if(AttachedPIDFID==null)
            {
                @ViewBag.IniAttachedPIDF = false;
            }
            else
            {
                @ViewBag.IniAttachedPIDF = true;
            }

            @ViewBag.IniInitializationID = data.InitializationID;
            @ViewBag.IniCountryID = data.CountryID;
            @ViewBag.IniCountry = data.Country;
            @ViewBag.IniGenericName = data.GenericName;
            @ViewBag.IniBrandName = data.BrandName;
            @ViewBag.IniTreadmarkApprovedInternal = data.TreadmarkApprovedInternal;
            @ViewBag.IniTreadmarkSuggestedInternal = data.TreadmarkSuggestedInternal;
            @ViewBag.IniTreadmarkOwnerInternal = data.TreadmarkOwnerInternal;
            @ViewBag.IniForm = data.Form;
            @ViewBag.IniStrength = data.Strength;
            @ViewBag.IniPackSize = data.PackSize;
            @ViewBag.IniPackStyle = data.PackStyle;
            @ViewBag.IniPlant = data.Plant;
            @ViewBag.IniCurrency = data.Currency;
            @ViewBag.IniRegistrationFees = data.RegistrationFees;
            @ViewBag.IniFeesToBePaidBy = data.FeesToBePaidBy;
            @ViewBag.IniModeOfFeesPayment = data.ModeOfFeesPayment;
            @ViewBag.IniMAHolder = data.MAHolder;
            @ViewBag.IniProposedMarketingStatus = data.ProposedMarketingStatus;
            @ViewBag.IniShippingPort = data.ShippingPort;
            @ViewBag.IniModeOfShipment = data.ModeOfShipment;
            @ViewBag.IniIncoterms = data.Incoterms;
            @ViewBag.IniDossierSubmittedToMOHBy = data.DossierSubmittedToMOHBy;
            @ViewBag.IniOwnerOfRegistration = data.OwnerOfRegistration;
            @ViewBag.IniAvailabilityofCDA = data.AvailabilityofCDA;
            @ViewBag.IniMarketSize = data.MarketSize;
            @ViewBag.IniThreeYearCAGR = data.ThreeYearCAGR;
            @ViewBag.IniNumberOfCurrentPlayer = data.NumberOfCurrentPlayer;
            @ViewBag.IniInnovatorBrand = data.InnovatorBrand;
            @ViewBag.IniFirstBrand = data.FirstBrand;
            @ViewBag.IniSecondBrand = data.SecondBrand;
            @ViewBag.IniThirdBrand = data.ThirdBrand;
            @ViewBag.IniExpectedMarketValueGrowth = data.ExpectedMarketValueGrowth;
            @ViewBag.IniInnavotorName = data.InnavotorName;

ExistingApplication/EmcureCERI.Web/Views/DRFInitialization/ProjectList.cshtml
@inject Microsoft.Extensions.Localization.IStringLocalizer<SharedResource> SharedLocalizer
@{
    ViewData["Title"] = "ProjectList";
}
<style>
	table.dataTable.dtr-inline.collapsed > tbody > tr[role="row"] > td.dtr-control:before, table.dataTable.dtr-inline.collapsed > tbody > tr[role="row"] > th.dtr-control:before {
		top: 24px;
	}
</style>

<div class="content-wrapper">
    <section class="content pt-3">
        <div class="container-fluid">
            <div class="row">
                <section class="col-lg-12">
                    <!-- Custom tabs (Charts with tabs)-->
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                <i class="far fa-copy mr-2"></i> Dossier List
                            </h3>
                            <div class="card-tools md-left">
                                <div class="mybtn-group">
                                        <a class="btn btn-primary" href="@Url.Action("GanttSummary","GanttNew")"><i class="fas fa-project-diagram mr-2"></i>Dossier Gantt Chart</a>
                                    
                                        <a class="btn btn-primary" href="@Url.Action("ProjectList","DRFInitialization")"><i class="far fa-copy mr-1"></i>Dossier List</a>
                                    
                                        <a class="btn btn-primary" href="@Url.Action("Index","DRFInitialization")"><i class="far fa-list-alt mr-1"></i>DRF</a>
                                    
                                        <a class="btn btn-primary" href="@Url.Action("DRFInitialization","DRFInitialization")"><i class="far fa-plus-square mr-1"></i> Create New DRF</a>
                                    
                                        <div class="export-btn mybtn-group"></div>
                                    
                                </div>
                            </div>
                        </div>
                        
                        <div class="card-body">
                            <div class="table-responsive">
                                <table id="DRFTable" class="table table-bordered table-striped table-hover dt-responsive nowrap" width="100%">
                                    <thead>
                                        <tr>
                                            <th>@SharedLocalizer["Id"].Value</th>
                                            <th>@SharedLocalizer["Dossier No"].Value</th>
                                            <th>@SharedLocalizer["Project Name"].Value</th>
                                            <th>@SharedLocalizer["Country"].Value</th>
                                            <th>@SharedLocalizer["Generic Name"].Value</th>
                                            <th>@SharedLocalizer["Brand Name"].Value</th>
                                            <th>@SharedLocalizer["Order Frequency"].Value</th>
                                            <th>@SharedLocalizer["Strength"].Value</th>
                                            <th>@SharedLocalizer["Pack Size"].Value</th>
                                            <th>@SharedLocalizer["Pack Style"].Value</th>
                                            <th>@SharedLocalizer["Form"].Value</th>
                                            <th>@SharedLocalizer["Plant"].Value</th>
                                            <th>@SharedLocalizer["Incoterms"].Value</th>
                                            <th>@SharedLocalizer["MA Holder"].Value</th>
                                            <th>@SharedLocalizer["Dossier to be sent"].Value</th>
                                            <th>@SharedLocalizer["Project Manager"].Value</th>
                                            <th>@SharedLocalizer["Dossier Template"].Value</th>
                                            <th>@SharedLocalizer["Status"].Value</th>
                                            <th>@SharedLocalizer["Final Approved"].Value</th>

                                        </tr>
                                    </thead>
                                </table>
                            </div>
                            

                        </div>

                    </div>
                </section>
            </div>


        </div>
    </section>

</div>


@section Scripts {
    <script>           


        $(document).ready(function () {
            var dataTable = $('#DRFTable').DataTable({
               @* order: [[1, "desc"]], *@
                order: [],
                ajax: "@Url.Action("GetFinalApprovedProjectList", "DRFInitialization")/",
                responsive: true,
                columnDefs: [					
                    { responsivePriority: 1, targets: 0 },
					{ responsivePriority: 2, targets: 5 },
                    { responsivePriority: 3, targets: -4 },                     
                     { responsivePriority: 4, targets: -1 }									
					
                ],
                "dom": 'Bfrtip',
                "buttons": [
                    {
                        "extend": 'excel', "text": '<i class="far fa-file-excel mr-1"></i> Export In Excel ', "className": "btn-primary", "exportOptions": {
                            "columns": ':visible'
                        }
                    },
                    { "extend": 'colvis', "className": "btn-primary" }
                ],
                columns: [
                    { "data": "initializationID" },					
                    { "data": "drfNo" },
                    { "data": "projectName" },
                    { "data": "countryName" },
                    { "data": "genericName" },
                    { "data": "brandName" },
                    { "data": "orderFrequency" },
                    { "data": "strengthName" },
                    { "data": "packSizeName" },
                    { "data": "packStyleName" },
                    { "data": "formName" },
                    { "data": "plantName" },
                    { "data": "incotermsName" },
                    { "data": "maHolder" },
                    { "data": "nameDossierSend" },
                    { "data": "projectManager" },
                    { "data": "dossierTemplate" },
                    { "data": "status" },
					{ "data": "final_Approved_Date" }
					
                ]
            });
            dataTable.draw().buttons().container().appendTo('.export-btn');
            $(".buttons-excel").removeClass("btn-secondary");
            $(".buttons-collection").removeClass("btn-secondary");
        });


    </script>
}